version: '3.8'
services:
    app:
        build: .
        image: laravel-si-pencatatan-besi-tua
        container_name: laravel-si-pencatatan-besi-tua
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/laravel-si-pencatatan-besi-tua
        volumes:
            - .:/var/www/laravel-si-pencatatan-besi-tua
            - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: nginx-si-pencatatan-besi-tua
        restart: unless-stopped
        tty: true
        ports:
            - "2022:80"
        volumes:
            - .:/var/www/laravel-si-pencatatan-besi-tua
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - app-network

    db:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: si-pencatatan-besi-tua
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
        ports:
            - "20222:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpma-si-pencatatan-besi-tua
        restart: always
        ports:
            - "7000:80"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
